services:
  mongo:
    image: mongo:6
    container_name: flux-mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: flux-server
    ports:
      - "${SERVER_PORT}:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - PORT=${SERVER_PORT}
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/
            - "*.log"
        - action: rebuild
          path: ./server/package.json

  client:
    build: ./client
    container_name: flux-client
    ports:
      - "${CLIENT_PORT}:5173"
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL=http://localhost:${SERVER_PORT}
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/
            - "*.log"
        - action: rebuild
          path: ./client/package.json

volumes:
  mongo-data:
