services:
  mongo:
    image: mongo:6
    container_name: flux-mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: flux-server
    ports:
      - "${SERVER_PORT}:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - PORT=${SERVER_PORT}
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: flux-client
    ports:
      - "${CLIENT_PORT}:5173"
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL=http://localhost:${SERVER_PORT}
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo-data:
